apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-calculator-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: "https://github.com/nasrinioo/tax-calculator-cloud-native.git"
    - name: revision
      value: "main"
  workspaces:
    - name: shared-workspace
      emptyDir: {}
